// This is automatically generated by CodeBind. Please do not modify it.

namespace GameApp.Hotfix.UI
{
    public partial class LanguageFormView
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_BackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Toggle m_ChineseToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ChineseBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ChineseCheckmarkImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_ChineseLabelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ChineseNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Toggle m_EnglishToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_EnglishBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_EnglishCheckmarkImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_EnglishLabelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_EnglishNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.ToggleGroup m_LanguageNodeToggleGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.VerticalLayoutGroup m_LanguageNodeVerticalLayoutGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_LanguageTitleTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_OKButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_OKDescribeTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ViewNodeRectTransform;


    }
}
