// This is automatically generated by CodeBind. Please do not modify it.

namespace GameApp.Hotfix.GFEntity
{
    public partial class HostEntityView
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.SpriteRenderer m_AvatarSpriteRenderer;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.InputSystem.PlayerInput m_ControlNodePlayerInput;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform m_SelfNodeTransform;


    }
}
