// This is automatically generated by CodeBind. Please do not modify it.

namespace GameApp.UI
{
    public partial class LanguageFormView
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_BlackMaskImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ViewNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_BackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_LanguageTitleTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.VerticalLayoutGroup m_LanguageNodeVerticalLayoutGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.ToggleGroup m_LanguageNodeToggleGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ChineseNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Toggle m_ChineseToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ChineseBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ChineseCheckmarkImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_ChineseLabelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_EnglishNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Toggle m_EnglishToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_EnglishBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_EnglishCheckmarkImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_EnglishLabelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_SpanishNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Toggle m_SpanishToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_SpanishBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_SpanishCheckmarkImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_SpanishLabelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_PortugueseNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Toggle m_PortugueseToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_PortugueseBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_PortugueseCheckmarkImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_PortugueseLabelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_OKButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_OKDescribeTextMeshProUGUI;


        public UnityEngine.UI.Image BlackMaskImage => m_BlackMaskImage;
        public UnityEngine.RectTransform ViewNodeRectTransform => m_ViewNodeRectTransform;
        public UnityEngine.UI.Image BackgroundImage => m_BackgroundImage;
        public TMPro.TextMeshProUGUI LanguageTitleTextMeshProUGUI => m_LanguageTitleTextMeshProUGUI;
        public UnityEngine.UI.VerticalLayoutGroup LanguageNodeVerticalLayoutGroup => m_LanguageNodeVerticalLayoutGroup;
        public UnityEngine.UI.ToggleGroup LanguageNodeToggleGroup => m_LanguageNodeToggleGroup;
        public UnityEngine.RectTransform ChineseNodeRectTransform => m_ChineseNodeRectTransform;
        public UnityEngine.UI.Toggle ChineseToggle => m_ChineseToggle;
        public UnityEngine.UI.Image ChineseBackgroundImage => m_ChineseBackgroundImage;
        public UnityEngine.UI.Image ChineseCheckmarkImage => m_ChineseCheckmarkImage;
        public TMPro.TextMeshProUGUI ChineseLabelTextMeshProUGUI => m_ChineseLabelTextMeshProUGUI;
        public UnityEngine.RectTransform EnglishNodeRectTransform => m_EnglishNodeRectTransform;
        public UnityEngine.UI.Toggle EnglishToggle => m_EnglishToggle;
        public UnityEngine.UI.Image EnglishBackgroundImage => m_EnglishBackgroundImage;
        public UnityEngine.UI.Image EnglishCheckmarkImage => m_EnglishCheckmarkImage;
        public TMPro.TextMeshProUGUI EnglishLabelTextMeshProUGUI => m_EnglishLabelTextMeshProUGUI;
        public UnityEngine.RectTransform SpanishNodeRectTransform => m_SpanishNodeRectTransform;
        public UnityEngine.UI.Toggle SpanishToggle => m_SpanishToggle;
        public UnityEngine.UI.Image SpanishBackgroundImage => m_SpanishBackgroundImage;
        public UnityEngine.UI.Image SpanishCheckmarkImage => m_SpanishCheckmarkImage;
        public TMPro.TextMeshProUGUI SpanishLabelTextMeshProUGUI => m_SpanishLabelTextMeshProUGUI;
        public UnityEngine.RectTransform PortugueseNodeRectTransform => m_PortugueseNodeRectTransform;
        public UnityEngine.UI.Toggle PortugueseToggle => m_PortugueseToggle;
        public UnityEngine.UI.Image PortugueseBackgroundImage => m_PortugueseBackgroundImage;
        public UnityEngine.UI.Image PortugueseCheckmarkImage => m_PortugueseCheckmarkImage;
        public TMPro.TextMeshProUGUI PortugueseLabelTextMeshProUGUI => m_PortugueseLabelTextMeshProUGUI;
        public UnityEngine.UI.Button OKButton => m_OKButton;
        public TMPro.TextMeshProUGUI OKDescribeTextMeshProUGUI => m_OKDescribeTextMeshProUGUI;


    }
}
