// This is automatically generated by CodeBind. Please do not modify it.

namespace GameApp.UI
{
    public partial class DialogFormView
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_BlackMaskImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ViewNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_BackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_TitleBackgroundImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_TitleTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_MessageTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.HorizontalLayoutGroup m_ModeNodeHorizontalLayoutGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ConfirmNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_ConfirmButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_ConfirmDescribeTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_CancelNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_CancelButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_CancelDescribeTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_OtherNodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_OtherButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_OtherDescribeTextMeshProUGUI;


        public UnityEngine.UI.Image BlackMaskImage => m_BlackMaskImage;
        public UnityEngine.RectTransform ViewNodeRectTransform => m_ViewNodeRectTransform;
        public UnityEngine.UI.Image BackgroundImage => m_BackgroundImage;
        public UnityEngine.UI.Image TitleBackgroundImage => m_TitleBackgroundImage;
        public TMPro.TextMeshProUGUI TitleTextMeshProUGUI => m_TitleTextMeshProUGUI;
        public TMPro.TextMeshProUGUI MessageTextMeshProUGUI => m_MessageTextMeshProUGUI;
        public UnityEngine.UI.HorizontalLayoutGroup ModeNodeHorizontalLayoutGroup => m_ModeNodeHorizontalLayoutGroup;
        public UnityEngine.RectTransform ConfirmNodeRectTransform => m_ConfirmNodeRectTransform;
        public UnityEngine.UI.Button ConfirmButton => m_ConfirmButton;
        public TMPro.TextMeshProUGUI ConfirmDescribeTextMeshProUGUI => m_ConfirmDescribeTextMeshProUGUI;
        public UnityEngine.RectTransform CancelNodeRectTransform => m_CancelNodeRectTransform;
        public UnityEngine.UI.Button CancelButton => m_CancelButton;
        public TMPro.TextMeshProUGUI CancelDescribeTextMeshProUGUI => m_CancelDescribeTextMeshProUGUI;
        public UnityEngine.RectTransform OtherNodeRectTransform => m_OtherNodeRectTransform;
        public UnityEngine.UI.Button OtherButton => m_OtherButton;
        public TMPro.TextMeshProUGUI OtherDescribeTextMeshProUGUI => m_OtherDescribeTextMeshProUGUI;


    }
}
